export const RESPONSE_CODE = {
  SUCCESS: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
  },

  REDIRECTION: {
    MULTIPLE_CHOICE: 300,
  },

  CLIENT_ERROR: {
    INVALID_ARGUMENT: 400,
    FAILED_PRECONDITION: 400,
    UNAUTHENTICATED: 401,
    NOT_FOUND: 404,
  },

  SERVER_ERROR: {
    INTERNAL: 500,
    SERVICE_UNAVAILABLE: 503,
  },
};